spring:
  application:
    name: no_sql app
  profiles:
    active:
      - dev
  jpa:
    hibernate:
      ddl-auto: 'validate'
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true


  data:
    redis:
      host: localhost
      port: 6379
    mongodb:
      uri: mongodb://root:root@localhost:27017/nosqldb?authSource=admin

server:
  port: 8080

app:
  redis:
    enable: true
  cache:
    cache-names:
      - allTasks
      - taskById
      - allUsers
      - userById
    caches:
      allTasks:
        expiry: 5m
      taskById:
        expiry: 5m
      allUsers:
        expiry: 5m
      userById:
        expiry: 5m

  pubsub:
    topic: "nosql:pubsub"
